##########################################################################################
# Install standalone
##########################################################################################
# FROM ubuntu:24.04
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update && apt-get install -y curl && apt-get clean && rm -rf /var/lib/apt/lists/*
# RUN curl -LsSf https://astral.sh/uv/install.sh | sh
# CMD ["bash"]

##########################################################################################
# Install tied to specific python version (inside virtual envirnment)
##########################################################################################
FROM python:3.12-slim
WORKDIR /app
RUN apt-get update && apt-get install -y && python -m venv /app/.venv
RUN /app/.venv/bin/pip install uv

# # Option 1: Benchmark the installation
# CMD ["bash", "-c", "source /app/.venv/bin/activate && uv init && time uv add requests flask pygame pyqt6 django"]
# # CMD ["bash", "-c", "source /app/.venv/bin/activate && uv init && time uv add requests flask pygame pyqt6 pip-audit"]

# # Option 2: Just install uv and give shell with activated venv 
# RUN echo 'source /app/.venv/bin/activate' >> /root/.bashrc
# CMD ["bash"]

# # Option 3: Install everything and give shell with activated venv
# RUN echo 'source /app/.venv/bin/activate' >> /root/.bashrc
# CMD ["bash", "-c", "source /app/.venv/bin/activate && uv init && uv add requests flask pygame pyqt6 pip-audit && bash"]

# Option 3: Install everything and give shell with activated venv
CMD ["bash", "-c", "source /app/.venv/bin/activate && uv init && time uv add requests flask pygame pyqt6 pip-audit && time uv remove requests flask pygame pyqt6 pip-audit && time uv add requests flask pygame pyqt6 pip-audit"]

##########################################################################################
# Install manually, tied to specific python version
##########################################################################################
# FROM ubuntu:24.04
# ENV DEBIAN_FRONTEND=noninteractive
# RUN apt-get update && apt-get install -y curl vim python3 python3-pip python3.12-venv && apt-get clean
# RUN mkdir app
# RUN cd app && python3 -m venv .venv
# WORKDIR app

# source .venv/bin/activate
# pip install uv
# deactivate
# uv init
# uv add requests flask pygame pyqt6 pip-audit
# pip-audit